CREATE ROLE administrator WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:a+YL4d2yvpmBZEj6Ors+Gw==$oc2wgw3baedlLhhZIfUlQrsU2UX+ijQ7icO0kbmL4mI=:PyYzNzJjoQlfmKtDhvmgRackMpNiKkHm17nZzg67cSE=';

CREATE ROLE employee WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:IxXpJon6jYGRXmnu5pWD7A==$VbeEYHC3LLidU4eB8igvo60JuXtbEaOhV3rQ/eswTCA=:JGPgg5v7oHQzbKuqRnMPUrpL/ngWtK0OfWudjeiDmQ4=';

GRANT administrator TO employee;